logging:
  level:
    org.springframework: INFO
    org.hibernate.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  hateoas:
    use-hal-as-default-json-media-type: false