logging:
  level:
    org.springframework: INFO
    org.hibernate.sql: TRACE
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      write-dates-as-timestamps: false
      